const ws = new WebSocket('ws://localhost:9224/devtools/page/18C8DCB0884C5DE863CED52DD56F198D')
let id = 0; const pending = new Map()
const send = (method, params = {}) => new Promise((resolve) => {
  const mid = ++id; pending.set(mid, resolve); ws.send(JSON.stringify({ id: mid, method, params }))
})
ws.onmessage = (ev) => { const m = JSON.parse(ev.data); if (m.id && pending.has(m.id)) { pending.get(m.id)(m); pending.delete(m.id) } }
await new Promise((r) => (ws.onopen = r))
await send('Page.enable')
await send('Runtime.enable')
await send('Page.navigate', { url: 'https://www.xn--ykq321c.com/' })
await new Promise((r) => setTimeout(r, 20000))
const r1 = await send('Runtime.evaluate', { expression: 'location.href', returnByValue: true })
console.log('final URL:', r1.result.result.value)
const r2 = await send('Runtime.evaluate', { expression: 'document.title + " || " + document.body.innerText.slice(0, 400)', returnByValue: true })
console.log('page:', r2.result.result.value)
ws.close()
